version: "3.8"

services:
    mongo:
        image: mongo
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"
    login-app:
        depends_on:
            - mongo
        container_name: es6-node-express-mongo-docker-sample
        image: cronycles/es6-node-express-mongo-docker-sample
        restart: always
        build: .
        ports:
             - "7500:7500"
